### ISSUE TITLE
What are the different game modes?

### ISSUE THREAD

**Issue by nerist** [marloncassar/MarlonCassar-HnD-2#9]
I saw three different game modes what is the difference?

**Comment by marloncassar** [comment]
The game consists of three game modes : 

Arcade Mode - The user is presented with three different levels.

Time Attack -  Challenge your imagination, fight against the time and build a balanced stack. Be careful ! Shapes are spawn randomly. This is the Time Attack Mode. Boxes are spawn randomly challenge yourself. You’ve got only 30 seconds.

Survival Mode - This is a kind of endless mode, where the player plays this level without any limit on the number of crates one could place.
